# docker-compose.yml
version: '3.9'
services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"

  web:
    build: .
    command: sh -c "python bot.py"
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_POST_INTERVAL=10
      - REDIS_HOST=redis
    volumes:
      - .:/app

  celery-worker:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_POST_INTERVAL=10
      - REDIS_HOST=redis

  celery-beat:
    build: .
    command: celery -A tasks beat --loglevel=INFO
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_POST_INTERVAL=10
      - REDIS_HOST=redis
